[Graph Algo] Preparation Works
Arrow-air/lib-router pull request #3
Opened 2022-08-27 20:35 UTC by GoodluckH

Enhancements:
* Make current `Node` objects hashable and equitable
* Implement the haversine formula for computing distances between two geo points on a sphere. To test this, use the [online calculator](https://www.vcalc.com/wiki/vCalc/Haversine+-+Distance). Note that this online tool does not give 5 decimal precisions, but the whole number part should be roughly in the ballpark.

This haversine function is essentially a very simplified cost function for computing the weight of edges on a graph.

2022-08-29 15:55 UTC, ServiceDog requested changes

2022-08-29 15:55 UTC, amsmith-pro commented on src/types/node.rs
> +    fn distance_to(&self, other: &dyn AsNode) -> f32 {
Might want to return an ordered float, so you can sort based on distance_to

This would be important in an Emergency No-Fly situation where aircraft must find the nearest safe harbor

2022-08-30 00:21 UTC, GoodluckH commented on src/types/node.rs
> +    fn distance_to(&self, other: &dyn AsNode) -> f32 {
Resolved in [b6b6fad](https://github.com/Arrow-air/lib-router/pull/3/commits/b6b6fad958d5040425ac6995fd52d871896f5192)

2022-08-30 00:22 UTC, GoodluckH commented
Please use the pr-rebase github action to rebase and squash the fixup commit once you approve the pr.

2022-08-30 00:23 UTC, ServiceDog approved these changes, later dismissed

2022-08-30 00:24 UTC, ServiceDog commented
/autosquash

2022-08-30 00:26 UTC, ServiceDog commented
/rebase-autosquash

2022-08-30 00:43 UTC, ServiceDog approved these changes

2022-08-30 00:46 UTC, merged